spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: buybet
    password: password
    url: jdbc:postgresql://localhost:5432/buybet-user-board-database
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
file:
  user:
    profile-image-path: profile-image-dev-storage
security:
  token:
    secret: buybet-token-secret