version: '3.1'
services:
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=buybet
      - POSTGRES_DB=buybet-user-board-database